[project]
name = "gw-simulator"
version = "0.1.0"
description = "simulator library and CLI app to produce LIGO data for a binary black hole event"
readme = "README.md"
authors = [
    { name = "Peter Steinbach", email = "p.steinbach@hzdr.de" }
]
requires-python = "<3.13" #see https://github.com/ahnitz/ligo-segments/issues/1 and https://github.com/gwastro/pycbc/blob/9c44fd093f834f2df18cdc6bad62c224ab6a5b1f/setup.py#L268
dependencies = [
"h5py", #io
"hdf5plugin", #compression in hdf5
"torch", #simulator framework
"loguru", #CLI goodness
"click", #CLI helper
"bilby",
"lalsuite"
]
include-package-data = true

[project.optional-dependencies]
dev = ["pytest"]

[project.scripts]
gw-simulator = "gw_simulator:main"

[tool.setuptools.package-data]
include = ["src/gw_simulator/config/pycbc_config.ini"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
